# ruff: noqa: E501
TRIAGE_METHODOLOGY = """# Triage

Move issues on the project issue tracker through a small state machine of triage roles.

Every comment or issue posted to the issue tracker during triage **must** start with this disclaimer:

> *This was generated by AI during triage.*

## Roles

Two **category** roles:

- `bug` — something is broken
- `enhancement` — new feature or improvement

Five **state** roles:

- `needs-triage` — maintainer needs to evaluate
- `needs-info` — waiting on reporter for more information
- `ready-for-agent` — fully specified, ready for an AFK agent
- `ready-for-human` — needs human implementation
- `wontfix` — will not be actioned

Every triaged issue should carry exactly one category role and one state role. If state roles conflict, flag it and ask the maintainer before doing anything else.

State transitions: an unlabeled issue normally goes to `needs-triage` first; from there it moves to `needs-info`, `ready-for-agent`, `ready-for-human`, or `wontfix`. `needs-info` returns to `needs-triage` once the reporter replies. The maintainer can override at any time — flag transitions that look unusual and ask before proceeding.

## Show what needs attention

Query the issue tracker and present three buckets, oldest first:

1. **Unlabeled** — never triaged.
2. **`needs-triage`** — evaluation in progress.
3. **`needs-info` with reporter activity since the last triage notes** — needs re-evaluation.

Show counts and a one-line summary per issue. Let the maintainer pick.

## Triage a specific issue

1. **Gather context.** Read the full issue (body, comments, labels, reporter, dates). Parse any prior triage notes so you don't re-ask resolved questions. Explore the codebase using the project's domain glossary, respecting ADRs in the area. Read `.out-of-scope/*.md` and surface any prior rejection that resembles this issue.

2. **Recommend.** Tell the maintainer your category and state recommendation with reasoning, plus a brief codebase summary relevant to the issue. Wait for direction.

3. **Reproduce (bugs only).** Before any grilling, attempt reproduction: read the reporter's steps, trace the relevant code, run tests or commands. Report what happened — successful repro with code path, failed repro, or insufficient detail (a strong `needs-info` signal). A confirmed repro makes a much stronger agent brief.

4. **Grill (if needed).** If the issue needs fleshing out, run a grilling session.

5. **Apply the outcome:**
   - `ready-for-agent` — post an agent brief comment.
   - `ready-for-human` — same structure as an agent brief, but note why it can't be delegated.
   - `needs-info` — post triage notes.
   - `wontfix` (bug) — polite explanation, then close.
   - `wontfix` (enhancement) — write to `.out-of-scope/`, link to it from a comment, then close.
   - `needs-triage` — apply the role. Optional comment if there's partial progress.

## Agent Brief Template

When an issue moves to `ready-for-agent`, post a structured agent brief:

```markdown
## Agent Brief

**Category:** bug / enhancement
**Summary:** one-line description of what needs to happen

**Current behavior:**
Describe what happens now.

**Desired behavior:**
Describe what should happen after the agent's work is complete.

**Key interfaces:**
- `TypeName` — what needs to change and why
- `functionName()` return type — what it currently returns vs what it should return

**Acceptance criteria:**
- [ ] Specific, testable criterion 1
- [ ] Specific, testable criterion 2

**Out of scope:**
- Thing that should NOT be changed or addressed
```

Principles for agent briefs:
- **Durability over precision** — describe interfaces and behavioral contracts, not file paths or line numbers
- **Behavioral, not procedural** — describe WHAT, not HOW
- **Complete acceptance criteria** — every criterion should be independently verifiable
- **Explicit scope boundaries** — state what is out of scope

## Needs-info template

```markdown
## Triage Notes

**What we've established so far:**

- point 1
- point 2

**What we still need from you (@reporter):**

- question 1
- question 2
```

## Out-of-Scope Knowledge Base

The `.out-of-scope/` directory stores persistent records of rejected feature requests:

- One file per **concept**, not per issue
- File format: concept name, why out of scope, prior requests list
- During triage, check `.out-of-scope/` for matches with incoming issues
- Only write to `.out-of-scope/` when an enhancement is rejected as `wontfix`

## Quick state override

If the maintainer says "move #42 to ready-for-agent", trust them and apply the role directly. Confirm what you're about to do, then act. Skip grilling.

## Resuming a previous session

If prior triage notes exist on the issue, read them, check whether the reporter has answered any outstanding questions, and present an updated picture before continuing. Don't re-ask resolved questions.
"""


def execute(action: str = "show", issue_reference: str = "") -> dict:
    return {
        "skill": "triage",
        "methodology": TRIAGE_METHODOLOGY,
        "action": action,
        "issue_reference": issue_reference,
        "instructions": (
            "Apply the triage methodology. Follow the state machine for issue triage. "
            "Always start comments with the AI disclaimer. Use domain glossary vocabulary."
        ),
    }
